apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  strategy: {}
  template:
    metadata:
      annotations:
        dapr.io/app-id: shipping
        dapr.io/app-port: "3004"
        dapr.io/config: appconfig
        dapr.io/enabled: "true"
        dapr.io/metrics-port: "42339"
        dapr.io/unix-domain-socket-path: ""
      creationTimestamp: null
      labels:
        app: shipping
    spec:
      containers:
      - env:
        - name: APP_ID
          value: shipping
        - name: APP_CHANNEL_ADDRESS
        - name: APP_PORT
          value: "3004"
        - name: DAPR_METRICS_PORT
          value: "42339"
        image: ttl.sh/shipping-8158471@sha256:2c84c42f74c6e672d947daf53d89dc9c06eeac3944c90dd203425f6f779f98d0
        imagePullPolicy: Always
        name: shipping
        ports:
        - containerPort: 3004
        resources: {}
