apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  strategy: {}
  template:
    metadata:
      annotations:
        dapr.io/app-id: inventory
        dapr.io/app-port: "3002"
        dapr.io/config: appconfig
        dapr.io/enabled: "true"
        dapr.io/metrics-port: "36993"
        dapr.io/unix-domain-socket-path: ""
      creationTimestamp: null
      labels:
        app: inventory
    spec:
      containers:
      - env:
        - name: APP_ID
          value: inventory
        - name: APP_CHANNEL_ADDRESS
        - name: APP_PORT
          value: "3002"
        - name: DAPR_METRICS_PORT
          value: "36993"
        image: ttl.sh/inventory-1799997@sha256:d1ff555cc13594866c9e91918954c329685c880fec5fc06f285651301efd42e5
        imagePullPolicy: Always
        name: inventory
        ports:
        - containerPort: 3002
        resources: {}
