apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  strategy: {}
  template:
    metadata:
      annotations:
        dapr.io/app-id: payments
        dapr.io/app-port: "3003"
        dapr.io/config: appconfig
        dapr.io/enabled: "true"
        dapr.io/metrics-port: "39913"
        dapr.io/unix-domain-socket-path: ""
      creationTimestamp: null
      labels:
        app: payments
    spec:
      containers:
      - env:
        - name: APP_PORT
          value: "3003"
        - name: DAPR_METRICS_PORT
          value: "39913"
        - name: APP_ID
          value: payments
        - name: APP_CHANNEL_ADDRESS
        image: ttl.sh/payments-6828100@sha256:81a3171344efd92582d03779bd65885b0cc177c42d39a908d189bd03f95d4cdf
        imagePullPolicy: Always
        name: payments
        ports:
        - containerPort: 3003
        resources: {}
