apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  strategy: {}
  template:
    metadata:
      annotations:
        dapr.io/app-id: payments
        dapr.io/app-port: "3003"
        dapr.io/config: appconfig
        dapr.io/enabled: "true"
        dapr.io/metrics-port: "37419"
        dapr.io/unix-domain-socket-path: ""
      creationTimestamp: null
      labels:
        app: payments
    spec:
      containers:
      - env:
        - name: APP_ID
          value: payments
        - name: APP_CHANNEL_ADDRESS
        - name: APP_PORT
          value: "3003"
        - name: DAPR_METRICS_PORT
          value: "37419"
        image: ttl.sh/payments-4823648@sha256:10a293dfaf3082b7bb29fa147185f6fe51e35a7d3f7b276ddb27f72421f70279
        imagePullPolicy: Always
        name: payments
        ports:
        - containerPort: 3003
        resources: {}
