apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  strategy: {}
  template:
    metadata:
      annotations:
        dapr.io/app-id: notifications
        dapr.io/app-port: "3001"
        dapr.io/config: appconfig
        dapr.io/enabled: "true"
        dapr.io/metrics-port: "34425"
        dapr.io/unix-domain-socket-path: ""
      creationTimestamp: null
      labels:
        app: notifications
    spec:
      containers:
      - env:
        - name: APP_PORT
          value: "3001"
        - name: DAPR_METRICS_PORT
          value: "34425"
        - name: APP_ID
          value: notifications
        - name: APP_CHANNEL_ADDRESS
        image: ttl.sh/notifications-1298129@sha256:e8cf0c51e16d9910bdae1e5b32daae6a50fe20365c2a4b594b7e74557057c635
        imagePullPolicy: Always
        name: notifications
        ports:
        - containerPort: 3001
        resources: {}
