apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  strategy: {}
  template:
    metadata:
      annotations:
        dapr.io/app-id: notifications
        dapr.io/app-port: "3001"
        dapr.io/config: appconfig
        dapr.io/enabled: "true"
        dapr.io/metrics-port: "38685"
        dapr.io/unix-domain-socket-path: ""
      creationTimestamp: null
      labels:
        app: notifications
    spec:
      containers:
      - env:
        - name: APP_ID
          value: notifications
        - name: APP_CHANNEL_ADDRESS
        - name: APP_PORT
          value: "3001"
        - name: DAPR_METRICS_PORT
          value: "38685"
        image: ttl.sh/notifications-5473000@sha256:e3eb3f89d00bbd8a54dd73034d69a0ff25aca2c43bf88b98da8caf7532efdd26
        imagePullPolicy: Always
        name: notifications
        ports:
        - containerPort: 3001
        resources: {}
