apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    app: notifications
  type: LoadBalancer
